language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t tlinford/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true tlinford/docker-react npm run test